@startuml Blocks_Module_Class_Diagram

Interface EnergyBalance {
    --Mandatory Methods for all Realizations--
    fn energy_balance_check(energy_in : Energy, energy_out : Energy) : bool {} 
}

Interface MassBalance {
    --Mandatory Methods for all Realizations--
    fn material_balance_check(mass_in : Mass, mass_out : Mass) : bool {}  
}

Interface Block {
    --Mandatory Methods for all Realizations--
    + fn connect_input(&mut self, stream: &mut Stream) -> Result<(), &str>
    + fn disconnect_input(&mut self, stream: &mut Stream) -> Result<(), &str>
    + fn connect_output(&mut self, stream: &mut Stream) -> Result<(), &str>
    + fn disconnect_output(&mut self, stream: &mut Stream) -> Result<(), &str>
}


Struct Mixer {
  + id: u64,
  + inputs: Vec<Box<Stream>>
  + outputs: Vec<Box<Stream>>
  --Public Methods--
  + pub fn new(id : u64) -> Mixer {}
}

Mixer ..|> EnergyBalance
Mixer ..|> MassBalance
Mixer ..|> Block

note right of Mixer
  Mixer struct will also implement "Clone."
end note

@enduml

