@startuml Blocks_Module_Class_Diagram

Interface EnergyBalance {
  energy_balance_check(energy_in : Energy, energy_out : Energy) : bool {} 
}

Interface MassBalance {
  material_balance_check(mass_in : Mass, mass_out : Mass) : bool {}  
}


Interface ElementBalance {
  element_balance_check(stream_in : Vec<connector>, stream_out : Vec<connector>) : bool {}
}





Struct Mixer {
  - int id
  - int Xcord
  - int Ycord
  + String name
  + Vec<connectors> in_streams
  + Vec<connectors> out_streams

  ---Public Methods--
  + pub fn compute_flow_out() : connector {}
  ---Private Methods--
  - fn compute phase_fractions() {}
  - fn temperature_out() {}
  - fn pressure_out() {} 
}

EnergyBalance --> Mixer
MassBalance --> Mixer


@enduml

