@startuml properties_module_class_diagram
    
enum ChemicalIdentifier() {
    + PubchemID : int
    + CompoundName : string
}

Struct Chemical {
    + pubchem
}

Struct ChemicalProperties {}

Interface PropertyLibrary {}

@enduml
