@startuml properties_module_class_diagram
    
enum ChemicalIdentifier {
    + PubchemID : int
    + CompoundName : string
}

Struct Chemical {
    + pubchem::Compound pubchem_obj
    + ChemicalProperties properties
    --Public Methods--
    + fn new() -> Self
}

note left of Chemical
  "Chemical" struct will be dependent on external library "pubchem"
end note


Struct ChemicalProperties {}

Chemical --> ChemicalProperties
Chemical --> ChemicalIdentifier

@enduml
