@startuml activity_eos_class_diagrams

!include ./ideal-eos-module.puml

Interface ActivityEOSModel {

}

Struct Wilson {

}

Struct NRTL {

}

Struct UNIFAC {

}

Struct UNIQUAC {

}

ActivityEOSModel --> BaseEOSModel

Wilson ..|> ActivityEOSModel
NRTL ..|> ActivityEOSModel
UNIFAC ..|> ActivityEOSModel
UNIQUAC ..|> ActivityEOSModel

@enduml
