@startuml cubic_eos_class_diagram

!include ./ideal-eos-module.puml


Interface CubicEOSModel {

}


Struct VDW {

}

Struct PR {

}

Struct RKPR {

}

Struct RK {

}

Struct KU {

}

Struct PatelTejas {

}

CubicEOSModel --> BaseEOSModel
VDW ..|> CubicEOSModel
RK ..|> CubicEOSModel
RKPR --> RK
PR ..|> CubicEOSModel
KU ..|> CubicEOSModel
PatelTejas ..|> CubicEOSModel


@enduml
