@startuml ideal_gas_package_class_design


Struct IdealGasPackage {
  + temperature : *ThermodynamicTemperature
  + pressure : *Pressure
  + species_list : *Vec<ComponentData>
  + total_mass : *Mass
  + total_vol : *Volume
  + total_mol : *AmountOfSubstance 
  ---Public Methods---
  
}


@enduml
