@startuml ideal_gas_package_class_design


Struct IdealGasPackage {
  + *ThermodynamicTemperature temperature
  + *Pressure pressure
  + *Vec<ComponentData> species_list
  + *Mass total_mass
  + *Volume total_vol
  + *AmountOfSubstance total_mol
  ---Public Methods---
  
}


@enduml
