@startuml ideal_eos_class_diagram

Interface BaseEOSModel {

}

Struct BaseIdeal {

}

Struct ReidPolynomial {

}

Struct JobackMethod {

}

Struct WalkerModel {

}

BaseEOSModel ..|> BaseIdeal
BaseEOSModel ..|> ReidPolynomial
BaseEOSModel ..|> JobackMethod
BaseEOSModel ..|> WalkerModel

@enduml
