@startuml thermodynamics_module_class_diagram
skinparam linetype ortho

!include ./thermo-packages/cubic-eos-module.puml
!include ../stream-module/connector-module.puml

enum ThermodynamicConstants {
    + UniversalGasConstant
    + StandardTemperature
    + StandardPressure
    + AvogadroNumber
    --Public Methods--
    + fn value(&self) : Box<dyn std::any::Any> {}
}

enum EOSParams<T> {
    Single: Vec<T>
    Pair: Vec<Vec<T>>
}

Interface BaseEOSModel {

}

Interface BaseThermoProperties {

}



StreamThermoState --> ThermoProperties :uses
ThermoProperties --> BaseThermodynamicConstants


@enduml
