@startuml thermodynamics_module_class_diagram
skinparam linetype ortho


enum ThermodynamicConstants {
    + UniversalGasConstant
    + StandardTemperature
    + StandardPressure
    + AvogadroNumber
    --Public Methods--
    + fn value(&self) : Box<dyn std::any::Any> {}
}

enum EOSParams<T> {
    Single: Vec<T>
    Pair: Vec<Vec<T>>
}


StreamThermoState --> BaseThermoSupportingMethods :uses
ThermoProperties --> ThermodynamicConstants


@enduml
